### ISSUE TITLE
Support node_exporter >=0.15.0

### ISSUE THREAD

**Issue by tereschenkov** [UnderGreen/ansible-prometheus-node-exporter#18]
Role is not working with node_exporter >= 0.15.0

Due to https://github.com/prometheus/node_exporter/pull/640 and https://github.com/prometheus/node_exporter/pull/639 changes, templates that generate systemd/init/etc configuration files need to be updated to use new flags structure

**Comment by Sispheor** [comment]
I confirm, it's one `--collector.<name>` per collector.
Do you accept PR?
Do you want to keep your role working with version < 15?

**Comment by UnderGreen** [comment]
I accept PR's.
But.. what is so bad, I don't have free time to create PR's.

**Comment by Sispheor** [comment]
I'm on it

**Comment by protheantom** [comment]
Fantastic!! @UnderGreen please, could you do a release, here or at ansible-galaxy?

Thanks!

**Comment by Sispheor** [comment]
This is done. Can be closed.
