### ISSUE TITLE
"AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'

### ISSUE THREAD

**Issue by cristian04** [UnderGreen/ansible-prometheus-node-exporter#3]
Hi, 

Im receiving this random issue after upgrading. Any idea?

```
TASK [UnderGreen.prometheus-node-exporter : create systemd service unit] *******
Thursday 23 March 2017  16:58:03 +1300 (0:00:00.286)       0:01:10.353 ********
fatal: [images-worker]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}
```

**Comment by kermit832** [comment]
I'm sure you got this sorted but you need to change `prometheus_node_exporter_config_flags.iteritems()`  to `prometheus_node_exporter_config_flags.items()`. This was an issue for me since i'm using python3.

**Comment by roumano** [comment]
Bug confirmed (on a strech debian OS) & Fix confirmed too

**Comment by andrewrothstein** [comment]
this means Ansible behaves differently under python2 and python3? that makes role authoring more complex. is there some shim that I can use to iterate over a dictionary from my yaml defaults/vars?

if I wanted to add one would it be a jinja2 filter or am I overthinking this?

**Comment by roumano** [comment]
this means Ansible behaves differently under python2 and python3?
> Yes : 
- https://docs.ansible.com/ansible/2.5/user_guide/playbooks_python_version.html
- https://docs.ansible.com/ansible/2.5/dev_guide/testing/sanity/no-dict-iteritems.html

**Comment by scottalan** [comment]
Unless I'm reading this wrong `items()` can be used in both Python2 and 3

https://docs.ansible.com/ansible/latest/user_guide/playbooks_python_version.html#dict-iteritems

> Playbooks and Jinja2 templates should use dict.keys(), dict.values(), and dict.items() in order to be compatible with both Python2 and Python3
