### ISSUE TITLE
Version 1.5.0 not available on Ansible Galaxy

### ISSUE THREAD

**Issue by avishefi** [UnderGreen/ansible-prometheus-node-exporter#52]
Version 1.5.0 is not available on Ansible Galaxy

**Comment by roumano** [comment]
No, the name is correct, he need to import again on galaxy
@UnderGreen , can you import again in order to permit to use the lastest version by default ?

**Comment by avishefi** [comment]
@roumano thanks, updated title and description

**Comment by UnderGreen** [comment]
Imported 1.5.1

**Comment by Geod24** [comment]
> No, the name is correct, he need to import again on galaxy

Not quite, because all the other tags use `v` as a prefix. This seems to trip ansible up when no explicit version is provided. `ansible-lint` will warn about it for example.

**Comment by avishefi** [comment]
Looks good now on Ansible Galaxy, thanks!
